Extracts built-in config

diff --git a/.github/workflows/checkstyle.yml b/.github/workflows/checkstyle.yml
--- a/.github/workflows/checkstyle.yml
+++ b/.github/workflows/checkstyle.yml
@@ -1,6 +1,9 @@
-# This workflow will build a Java project with Gradle
-# For more information see:
-#  https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
+# This workflow will build check Java sources using Checkstyle linter.
+#
+# By design, it is expected to only analyse files affected by given pull request,
+# and not the whole source tree.
+#
+# Marcin Orlowski
 
 name: "Checkstyle"
 on:
@@ -13,12 +16,13 @@ on:
 
 jobs:
   analyze_sources:
-    name: "Do we need to lint the sources?"
+    name: "Is there anything to lint?"
     runs-on: ubuntu-latest
 
     outputs:
       # Export 'filter' step check result so next step can use it.
       run_checkstyle: ${{ steps.filter.outputs.src }}
+      # These are source files matching our filter  that are affected by the PR.
       changed_files: ${{ steps.filter.outputs.src_files }}
 
     steps:
@@ -30,7 +34,7 @@ jobs:
       uses: actions/checkout@v2
 
       # https://github.com/marketplace/actions/paths-changes-filter
-    - name: "Look for changes in monitored locations"
+    - name: "Look for changes that matters for us..."
       uses: dorny/paths-filter@v2
       id: filter
       with:
@@ -57,12 +61,43 @@ jobs:
     needs: analyze_sources
     if: needs.analyze_sources.outputs.run_checkstyle == 'true'
 
+    # Checkstyle is painful to be used from command line as apparently its deves never learnt
+    # to use one (see radiculous comments https://github.com/checkstyle/checkstyle/issues/8418)
+    # So some trickery have to be done to convince Checkstyle to do what we want as we use
+    # built-in "Google Checks" style with just some exceptions. Unfortunately you cannot just
+    # make it use these checks w/o having own config XML that re-defines it, which is pointless
+    # as suppressions are only thing we want to maintain (and to not care if Checkstyle's config
+    # format changed or not).
+
     steps:
+    - name: "Install packages..."
+      run: sudo apt-get install checkstyle unzip
+
     - name: "Checkout sources"
       uses: actions/checkout@v2
 
     - name: "Lint changed files"
+      # We need bash here as java-wrappers.sh may not work with other shells.
+      shell: bash
       run: |
+        echo "Using $(checkstyle --version)"
+
+        # Find where checkstyle.jar lives and get built-in google_checks.xml config out of it.
+        source /usr/lib/java-wrappers/java-wrappers.sh
+        locate_jar checkstyle
+        if [[ -z "${found_jar}" ]]; then
+          echo "checkstyle.jar not found."
+          exit 1
+        fi
+
+        unzip -d . "${found_jar}" google_checks.xml
+        # Starting from 8.28, default checkstyle config looks for optional checkstyle-suppressions.xml
+        # (See https://github.com/checkstyle/checkstyle/issues/6946) so we just need to link ours
+        # and that should be sufficient.
+        ln -s config/checkstyle/suppressions.xml checkstyle-suppressions.xml
+
+        # Let's try to lint all the altered files
         for file in ${{ needs.analyze_sources.outputs.changed_files }}; do
-          echo "${file}"
+          checkstyle -c google_checks.xml "${file}"
         done
+
